# @format

version: "3"

volumes:
  guests:

services:
  db:
    image: postgres:14-alpine
    env_file:
      - postgres.env
    ports:
      - 3005:5432
    volumes:
      - guests:/var/lib/postgresql/data
